Workaround for snap whoami
With help from sergiusens: https://forum.snapcraft.io/t/help-needed-cannot-use-snapcraft-login-in-github-action/24777/3

diff --git a/.github/workflows/package_and_release.yml b/.github/workflows/package_and_release.yml
--- a/.github/workflows/package_and_release.yml
+++ b/.github/workflows/package_and_release.yml
@@ -65,7 +65,7 @@ jobs:
         if: ${{ fromJSON(env.SHOULD_BUILD) }}
         run: |
           echo ${{ secrets.SNAP_TOKEN }} | snapcraft login --with -
-          snapcraft whoami || "Cannot determine who am I"
+          snapcraft whoami || echo "Cannot determine who I am."
 
       - name: Review Snap
         if: ${{ fromJSON(env.SHOULD_BUILD) }}
