Update package_and_release.yml

diff --git a/.github/workflows/package_and_release.yml b/.github/workflows/package_and_release.yml
--- a/.github/workflows/package_and_release.yml
+++ b/.github/workflows/package_and_release.yml
@@ -63,6 +63,14 @@ jobs:
         if: ${{ fromJSON(env.SHOULD_BUILD) }}
         run: |
           sudo ufw disable
+          
+      - name: Snap Store Login
+        if: ${{ fromJSON(env.SHOULD_BUILD) }}
+        env: # Or as an environment variable
+          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
+        run: |
+          snapcraft login
+          snapcraft whoami || echo "Cannot determine who I am."
       
       - name: Build Snap
         if: ${{ fromJSON(env.SHOULD_BUILD) }}
@@ -71,12 +79,6 @@ jobs:
       - name: Check Files
         run: ls
       
-      - name: Snap Store Login
-        if: ${{ fromJSON(env.SHOULD_BUILD) }}
-        run: |
-          snapcraft login
-          snapcraft whoami || echo "Cannot determine who I am."
-
       - name: Review Snap
         if: ${{ fromJSON(env.SHOULD_BUILD) }}
         run: review-tools.snap-review ${{ env.SNAP_NAME }}*.snap
